language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ashraj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ashraj/docker-react npm run test


