language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ashirahraj09/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ashirahraj09/react-test npm run test

after_success:
    - docker build -t ashirahraj09/multi-client ./client
    - docker build -t ashirahraj09/multi-nginx ./nginx
    - docker build -t ashirahraj09/multi-server ./server
    - docker build -t ashirahraj09/multi-worker ./worker

# Log Into DOCKER CLI
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    - docker push ashirahraj09/multi-client
    - docker push ashirahraj09/multi-nginx
    - docker push ashirahraj09/multi-server
    - docker push ashirahraj09/multi-worker

deploy: 
    edge: true
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-387311439628"
    bucket_path: "multi-docker"
    on : 
        branch : master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY